sdk/third-party/Makefile

style:Delete OBJECTS_DIR

---

sdk/wallet/boatwallet.c

refactor: set a default value for boat wallet private key in boatwallet.c file.

refactor: set a default value for boat wallet private key.

---

vendor/common/crypto/mbedTLS/include/mbedtls/config.h

refactor(mbedtls): note macro MBEDTLS_CHACHA20_C in mbedtls/config.h

refactor(mbedtls): note macro MBEDTLS_CHACHA20_C in mbedtls/config.h

---

vendor/common/crypto/mbedTLS/include/mbedtls/config.h

refactor: Delete MBEDTLS_POLY1305_C in config.h

refactor: Delete MBEDTLS_POLY1305_C in config.h

---

sdk/wallet/api_hlfabric.c

refactor:This condition is always true

refactor:This condition is always true

---

demo/Makefile

updated demo makefile

---

demo/demo_fabric/demo_fabric_abac.c
include/protocolapi/api_hlfabric.h
sdk/wallet/api_hlfabric.c

1.One is submit,the other is evaluate.Use BoatHlfabricTxEvaluate() to get states from hyperledger facric.Use BoatHlfabricTxSubmit to set states to hyperledger facric.Add BoatHlfabricTxEvaluate() in two files.
2.Change the affected demo.
3.Change BOAT_HLFABRIC_ARGS_MAX_NUM from 4 to 10.
4.Change BOAT_HLFABRIC_HTTP2_SEND_BUF_MAX_LEN from 4096 to 8192.
The change is tested use hyperledger facric2.2.
The reason why I Change BOAT_HLFABRIC_ARGS_MAX_NUM and BOAT_HLFABRIC_HTTP2_SEND_BUF_MAX_LEN is that because when I use the facric2.2 demo "basic",4 and 4096 is too small to use.

Fix:BoatHlfabricTxSubmit split into Two.

---

README.md

Candidate for BoAT-X-Framework V2.0.4 - RC2

Candidate for BoAT-X-Framework V2.0.4 - RC2

---

README.md

Candidate for BoAT-X-Framework V2.0.4 - RC3

Candidate for BoAT-X-Framework V2.0.4 - RC3

---

sdk/wallet/api_ethereum.c
sdk/wallet/api_fiscobcos.c
sdk/wallet/api_hlfabric.c
sdk/wallet/api_platone.c
sdk/wallet/boatversion.c
sdk/wallet/boatwallet.c

Modify the pointer parameter style to be consistent.

Modify the pointer parameter style to be consistent

---

include/boatplatform.h
vendor/common/crypto/mbedTLS/include/mbedtls/config.h
vendor/platform/linux-default/src/port_mbedtls/boatplatform.c

mbedtls  
using boat_calloc replace calloc
using boat_free replace free

mbedtls using boatcalloc replace calloc

---

sdk/wallet/api_fiscobcos.c

fix: Fixed an error calculating the length of blocklimit

---

SUPPORTED_LIST.md
demo/demo_fabric/demo_fabric_abac.c
docs/en-us/BoAT_System_Requirements_en.md
include/protocolapi/api_fiscobcos.h
include/protocolapi/api_platon.h
include/protocolapi/api_platone.h
sdk/wallet/api_fiscobcos.c
sdk/wallet/api_platon.c
sdk/wallet/api_platone.c
vendor/platform/linux-default/src/port_crypto_default/boatplatform_internal.c

BoAT-X-Framework V2.1.0
**Update Summary**
This is the first version of V2.1.x. A new feature *Node Discovery* is introduced, which allows the device to find available nodes around so that the client could decide send transaction or query to which node(s). This version also support Huawei's blockchain which is named BCS as well as some bugfix and documents update.

Candidate 2 for BoAT-X-Framework V2.1.0

---

vendor/common/crypto/mbedTLS/include/mbedtls/config.h

delete unuse function in mbedtls
Signed-off-by: yuanxinfei <792452536@qq.com>

feat(mbedtls/config.h)

---

demo/demo_hw_bcs/demo_hw_bcs.c
include/protocolapi/api_hlfabric.h
sdk/protocol/boathlfabric/boathlfabric_discovery.c
sdk/protocol/common/http2intf/http2intf.c
sdk/protocol/common/http2intf/http2intf.h
sdk/wallet/api_hlfabric.c
sdk/wallet/api_hw_bcs.c
vendor/platform/linux-default/src/port_crypto_default/boatplatform_internal.c
vendor/platform/linux-default/src/port_mbedtls/boatplatform_internal.c

Boatiotsdk http2 dev

---

tests/BoAT_ethereum_linuxDefault/01Wallet.c

PR:fix ethereum test case lack BoatIotSdkInit() and BoatIotSdkDeInit()

PR:fix ethereum test case lack BoatIotSdkInit() and BoatIotSdkDeInit()

---

tests/BoAT_ethereum_linuxDefault/01Wallet.c
tests/BoAT_ethereum_linuxDefault/02Parameters.c
tests/BoAT_ethereum_linuxDefault/03Transaction.c

PR: fix ethereum test case lack BoatIotSdkDeInit() and ck_assert

PR: fix ethereum test case lack BoatIotSdkDeInit() and ck_assert

---

tests/BoAT_platon_linuxDefault/01Wallet.c

PR: add BoatIotSdkInit() and delete BoatIotSdkDeInit() in platon test cases

PR: add BoatIotSdkInit() and delete BoatIotSdkDeInit() in platon test cases

---

tests/BoAT_platon_linuxDefault/01Wallet.c

PR:fix BoatIotSdkInit and BoatIotSdkDeInit and malloc issue

PR:fix BoatIotSdkInit and BoatIotSdkDeInit and malloc issue

---

tests/BoAT_platon_linuxDefault/01Wallet.c

fix the issue https://github.com/aitos-io/BoAT-X-Framework/issues/1050

PR: fix the issue aitos-io#1050

---

vendor/platform/Fibocom-L610/L610RootDirCode/CMakeLists.txt

PR: fix Fibocom-L610 documentation and code are inconsistent

---

tests/BoAT_ethereum_linuxDefault/01Wallet.c
tests/BoAT_platon_linuxDefault/01Wallet.c
tests/BoAT_platon_linuxDefault/02Parameters.c
tests/BoAT_platon_linuxDefault/tcase_entry.c

PR: fix the issue #1128 and #1129

PR: fix the issue #1128 and #1129 and #1141

---

tests/BoAT_platon_linuxDefault/01Wallet.c
tests/BoAT_platone_linuxDefault/01Wallet.c
tests/BoAT_platone_linuxDefault/tcase_entry.c
tests/BoAT_platone_linuxDefault/tcase_platone.h

PR: add platone wallet test cases #1176

PR: add platone wallet test cases #1176

---

tests/BoAT_platon_linuxDefault/02Parameters.c
tests/BoAT_platon_linuxDefault/03Transaction.c
tests/BoAT_platon_linuxDefault/tcase_entry.c
tests/BoAT_platone_linuxDefault/01Wallet.c
tests/BoAT_platone_linuxDefault/02Parameters.c
tests/BoAT_platone_linuxDefault/03Transaction.c
tests/BoAT_platone_linuxDefault/04Contract.c
tests/BoAT_platone_linuxDefault/my_contract.cpp.abi.c
tests/BoAT_platone_linuxDefault/my_contract.cpp.abi.h
tests/BoAT_platone_linuxDefault/tcase_entry.c
tests/BoAT_platone_linuxDefault/tcase_platone.h

PR: add platone Parameters and Transaction test cases

PR: add platone Parameters and Transaction test cases

---

Makefile
vendor/platform/mobiletek-L503C-6S/L503CRootDirCode/app/demo/Makefile
vendor/platform/mobiletek-L503C-6S/L503CRootDirCode/app/demo/demo_ethereum/Makefile
vendor/platform/mobiletek-L503C-6S/L503CRootDirCode/app/demo/demo_ethereum/demo_ethereum.c
vendor/platform/mobiletek-L503C-6S/L503CRootDirCode/app/demo/demo_ethereum/include/demo_ethereum.h
vendor/platform/mobiletek-L503C-6S/L503CRootDirCode/app/demo/main.c
vendor/platform/mobiletek-L503C-6S/Makefile
vendor/platform/mobiletek-L503C-6S/external.env
vendor/platform/mobiletek-L503C-6S/scripts/gen.py
vendor/platform/mobiletek-L503C-6S/src/Makefile
vendor/platform/mobiletek-L503C-6S/src/log/boatlog.h
vendor/platform/mobiletek-L503C-6S/src/port_crypto_default/Makefile
vendor/platform/mobiletek-L503C-6S/src/port_crypto_default/boatplatform.c
vendor/platform/mobiletek-L503C-6S/src/port_crypto_default/boatplatform_internal.c
vendor/platform/mobiletek-L503C-6S/src/port_mbedtls/Makefile
vendor/platform/mobiletek-L503C-6S/src/port_mbedtls/boatplatform.c
vendor/platform/mobiletek-L503C-6S/src/port_mbedtls/boatplatform_internal.c
vendor/platform/mobiletek-L503C-6S/src/rpc/Makefile
vendor/platform/mobiletek-L503C-6S/src/rpc/olhttpport.c
vendor/platform/mobiletek-L503C-6S/src/rpc/olhttpport.h
vendor/platform/mobiletek-L503C-6S/src/rpc/rpcintf.c
vendor/platform/mobiletek-L503C-6S/src/rpc/rpcport.h

PR: Migrate BoAT-X-Framework ethereum to mobiletek-L503C-6S platform

PR: Migrate BoAT-X-Framework ethereum to mobiletek-L503C-6S platform

---

vendor/platform/mobiletek-L503C-6S/README.md
vendor/platform/mobiletek-L503C-6S/README_en.md

PR: change L503 README.md and README_en.md

PR: change L503 README.md and README_en.md

---

Makefile
vendor/platform/Simcom-A7670C/BoatFabricDemo/README.md
vendor/platform/Simcom-A7670C/BoatFabricDemo/README_en.md
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_application.c
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_demo/inc/boat_platone_demo.h
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_demo/inc/my_contract.cpp.abi.h
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_demo/src/boat_platone_demo.c
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/README.md
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/README_en.md
vendor/platform/Simcom-A7670C/Makefile
vendor/platform/Simcom-A7670C/external.env
vendor/platform/Simcom-A7670C/scripts/gen.py
vendor/platform/Simcom-A7670C/src/Makefile
vendor/platform/Simcom-A7670C/src/log/boatlog.h
vendor/platform/Simcom-A7670C/src/port_crypto_default/Makefile
vendor/platform/Simcom-A7670C/src/port_crypto_default/boat_simcom_ssl.h
vendor/platform/Simcom-A7670C/src/port_crypto_default/boatplatform.c
vendor/platform/Simcom-A7670C/src/port_crypto_default/boatplatform_internal.c
vendor/platform/Simcom-A7670C/src/rpc/Makefile
vendor/platform/Simcom-A7670C/src/rpc/http_client.c
vendor/platform/Simcom-A7670C/src/rpc/http_client.h
vendor/platform/Simcom-A7670C/src/rpc/mbedhttpport.c
vendor/platform/Simcom-A7670C/src/rpc/mbedhttpport.h
vendor/platform/Simcom-A7670C/src/rpc/rpcintf.c
vendor/platform/mobiletek-L503C-6S/BoatFabricDemo/L503CRootDirCode/app/demo/boat_fabric_demo/boat_fabric_demo.c
vendor/platform/mobiletek-L503C-6S/BoatFabricDemo/README.md
vendor/platform/mobiletek-L503C-6S/BoatFabricDemo/README_en.md
vendor/platform/mobiletek-L503C-6S/BoatPlatoneDemo/README.md
vendor/platform/mobiletek-L503C-6S/BoatPlatoneDemo/README_en.md
vendor/platform/mobiletek-L503C-6S/src/port_crypto_default/boatplatform_internal.c

PR: merged fabric demo to Simcom A7670C

PR: merged fabric demo to Simcom A7670C

---

vendor/platform/Simcom-A7670C/BoatFabricDemo/A7670CRootDirCode/sc_application.c
vendor/platform/Simcom-A7670C/BoatFabricDemo/A7670CRootDirCode/sc_demo/inc/boat_fabric_demo.h
vendor/platform/Simcom-A7670C/BoatFabricDemo/A7670CRootDirCode/sc_demo/src/boat_fabric_demo.c
vendor/platform/Simcom-A7670C/BoatFabricDemo/BoAT-X-Framework/sdk/third-party/nghttp2/src/Makefile
vendor/platform/Simcom-A7670C/BoatFabricDemo/BoAT-X-Framework/sdk/third-party/protos/Makefile
vendor/platform/Simcom-A7670C/BoatFabricDemo/README.md
vendor/platform/Simcom-A7670C/BoatFabricDemo/README_en.md
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_application.c
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_demo/src/boat_platone_demo.c
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/A7670CRootDirCode/sc_demo/src/my_contract.cpp.abi.c
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/README.md
vendor/platform/Simcom-A7670C/BoatPlatoneDemo/README_en.md
vendor/platform/Simcom-A7670C/src/log/boatlog.h
vendor/platform/Simcom-A7670C/src/port_crypto_default/boatplatform_internal.c
vendor/platform/Simcom-A7670C/src/rpc/http_client.c

PR: added fabric demo integration specification for Simcom-A7670C and fix some bugs

PR: added fabric demo integration specification for Simcom-A7670C and fix some bugs

---

tests/UT/linuxDefault/blockchain/fabric/03Wallet.c
tests/UT/linuxDefault/blockchain/fabric/Makefile
tests/UT/linuxDefault/blockchain/fabric/tcase_fabric.h

PR: Add the url to the fabric test compile instruction

PR: Add the url to the fabric test compile instruction
